---
  AWSTemplateFormatVersion: '2010-09-09'
  Description: >
    Setup a Cloudera cluster for basic usage. All necessary parameters like node
    types, number of nodes, number of disks, their size and type are configurable.

  Parameters:
    clusterName:
      Description: Cluster name
      Default: cloudera.cluster.com
      Type: String
    clouderaVersion:
      Description: Cloudera version
      Default: 5.15.2
      Type: String
      AllowedValues: ['5.15.2', '5.14.4', '5.13.3', '5.12.2', '5.11.2']
    databaseType:
      Description: Database type
      Default: MySQL
      Type: String
      AllowedValues: ['MySQL', 'PostgreSQL']
    diskType:
      Description: AWS EBS volume type
      Default: st1
      Type: String
      AllowedValues: ['gp2', 'io1', 'st1']
    diskSize:
      Description: Size of AWS EBS volume in GB
      Default: 100
      Type: Number
    keyName:
      Description: AWS key pair used for creating nodes
      Type: AWS::EC2::KeyPair::KeyName
      AllowedPattern: ".+"
      ConstraintDescription: Please select existing key pair.
    instanceType:
      Description: AWS EC2 node type
      Default: m4.xlarge
      Type: String
      AllowedValues: [m4.xlarge, m4.2xlarge, m4.4xlarge, d2.xlarge, d2.2xlarge, d2.4xlarge]
  Metadata:
    AWS::CloudFormation::Interface:
      ParameterGroups:
        -
          Label:
            default: "Cloudera cluster parameters"
          Parameters:
            - clusterName
            - clouderaVersion
            - databaseType
        -
          Label:
            default: "AWS node parameters"
          Parameters:
            - diskType
            - diskSize
            - keyName
            - instanceType
  Mappings:
    SubnetConfig:
      VPC:
        CIDR: 172.24.0.0/16
      Public:
        CIDR: 172.24.0.0/24
      Private:
        CIDR: 172.24.8.0/22
    RegionMap:
      eu-west-1: # Ireland
        AMI: ami-0e12cbde3e77cbb98
      eu-west-2: # London
        AMI: ami-00846a67
  Resources:
    VPC:
      Type: AWS::EC2::VPC
      Properties:
        EnableDnsSupport: 'true'
        EnableDnsHostnames: 'true'
        CidrBlock:
          Fn::FindInMap:
            - SubnetConfig
            - VPC
            - CIDR
        Tags:
        - Key: Name
          Value: !Join ["-", [!Ref clusterName, "vpc"]]
    PublicSubnet:
      Type: AWS::EC2::Subnet
      Properties:
        VpcId:
          Ref: VPC
        CidrBlock:
          Fn::FindInMap:
          - SubnetConfig
          - Public
          - CIDR
        Tags:
        - Key: Name
          Value: !Join ["-", [!Ref clusterName, "public"]]
        - Key: Network
          Value: Public
    InternetGateway:
      Type: AWS::EC2::InternetGateway
      Properties:
        Tags:
        - Key: Name
          Value: !Join ["-", [!Ref clusterName, "ig"]]
    VPCGatewayAttachment:
      Type: AWS::EC2::VPCGatewayAttachment
      Properties:
        VpcId:
          Ref: VPC
        InternetGatewayId:
          Ref: InternetGateway
    PublicRouteTable:
      Type: AWS::EC2::RouteTable
      Properties:
        VpcId:
          Ref: VPC
        Tags:
        - Key: Name
          Value: !Join ["-", [!Ref clusterName, "public"]]
    PublicSubnetRouteTableAssociation:
      Type: AWS::EC2::SubnetRouteTableAssociation
      Properties:
        SubnetId:
          Ref: PublicSubnet
        RouteTableId:
          Ref: PublicRouteTable
    PublicRoute:
      Type: AWS::EC2::Route
      DependsOn: VPCGatewayAttachment
      Properties:
        RouteTableId:
          Ref: PublicRouteTable
        DestinationCidrBlock: 0.0.0.0/0
        GatewayId:
          Ref: InternetGateway
    ClouderaSecGroup:
      Type: AWS::EC2::SecurityGroup
      Properties:
        GroupDescription: "Installer Access"
        VpcId:
          Ref: VPC
        SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '22'
          ToPort: '22'
          CidrIp: 0.0.0.0/0
    ClouderaManager:
      Type: AWS::EC2::Instance
      DependsOn: VPCGatewayAttachment
      Properties:
        Tags:
          - Key: Name
            Value: !Join ["-", [!Ref clusterName, "ClouderaManager"]]
        ImageId:
          Fn::FindInMap:
          - RegionMap
          - Ref: AWS::Region
          - AMI
        KeyName:
          Ref: keyName
        InstanceType: !Ref instanceType
        NetworkInterfaces:
          - DeleteOnTermination: "true"
            DeviceIndex: 0
            AssociatePublicIpAddress: "true"
            SubnetId: !Ref PublicSubnet
            GroupSet:
              - !Ref ClouderaSecGroup
        BlockDeviceMappings:
          - DeviceName: "/dev/sdm"
            Ebs:
              VolumeType: !Ref diskType
              DeleteOnTermination: "true"
              VolumeSize: !Ref diskSize
        UserData:
          Fn::Base64: !Sub
            |
            #!/bin/bash
            echo "Instance is starting." > /tmp/run
            # Install MySql server.
            sudo yum install -y wget
            wget http://repo.mysql.com/mysql-community-release-el7-5.noarch.rpm
            sudo rpm -ivh mysql-community-release-el7-5.noarch.rpm
            yum -y update
            sudo yum install -y mysql-server
            sudo systemctl start mysqld

            # Unattended mysql_secure_installation.
            mysql -e "UPDATE mysql.user SET Password=PASSWORD('root') WHERE User='root';"
            mysql -e "DELETE FROM mysql.user WHERE User='root' AND Host NOT IN ('localhost', '127.0.0.1', '::1');"
            mysql -e "DELETE FROM mysql.user WHERE User='';"
            mysql -e "FLUSH PRIVILEGES;"

            # Create Cloudera services databases.
            mysql -e "create database database DEFAULT CHARACTER SET utf8;"

            # Download oracle jdk.
            wget --no-cookies --no-check-certificate --header "Cookie: gpw_e24=http%3A%2F%2Fwww.oracle.com%2F; oraclelicense=accept-securebackup-cookie" "https://download.oracle.com/otn-pub/java/jdk/8u201-b09/42970487e3af4f5aa5bca3f542482c60/jdk-8u201-linux-x64.rpm"
            sudo yum install -y jdk-8u201-linux-x64.rpm

            # Install Cloudera server packages.
            sudo yum-config-manager --add-repo=https://archive.cloudera.com/cm5/redhat/7/x86_64/cm/${clouderaVersion}/
            sudo yum install -y cloudera-manager-daemons cloudera-manager-server

            # Install Cloudera agent packages.
            sudo yum install -y cloudera-manager-agent

            sudo service cloudera-scm-agent start
            sudo service cloudera-scm-server start